version: "3.9"

services:
  db:
    image: postgres:14-alpine
    container_name: spc-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: C#P&ygM5
      POSTGRES_DB: space-probe-control-db
    restart: always

  api:
    build: "./"
    container_name: spc-api
    ports:
      - "8080:8080"
    depends_on:
      - "db"
